# Generated by Django 5.2.4 on 2025-07-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_id', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('departemen', models.CharField(max_length=100)),
                ('no_bpjs', models.CharField(blank=True, max_length=30, null=True)),
                ('akses_hp', models.BooleanField(default=False)),
                ('akses_laptop', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('can_scan_informasi', 'Dapat Scan Informasi Karyawan'), ('can_scan_benefit', 'Dapat Scan Benefit'), ('can_scan_kedisiplinan', 'Dapat Scan Kedisiplinan')],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('susu', 'Susu'), ('telur', 'Telur'), ('lainnya', 'Lainnya')], max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Kedisiplinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(choices=[('A', 'Alpha'), ('DT', 'Datang Terlambat'), ('PC', 'Pulang Cepat'), ('CX', 'Cuti Mendadak')], max_length=2)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='SuratPeringatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('SP1', 'SP1'), ('SP2', 'SP2'), ('SP3', 'SP3')], max_length=4)),
                ('tanggal_terbit', models.DateField()),
                ('tanggal_berlaku_sampai', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
        ),
    ]
