# Generated by Django 5.2.4 on 2025-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='no_bpjs',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='bpjs_k',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='BPJS Kesehatan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='bpjs_tk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='BPJS Ketenagakerjaan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='nik',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. KTP'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. HP'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='akses_hp',
            field=models.BooleanField(default=False, verbose_name='Izin Membawa HP'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='akses_laptop',
            field=models.BooleanField(default=False, verbose_name='Izin Membawa Laptop'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='no_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
