# Generated by Django 5.2.4 on 2025-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_karyawan_no_bpjs_karyawan_bpjs_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='jenis',
            field=models.CharField(choices=[('susu', 'Susu'), ('telur_susu', 'Telur + Susu'), ('lainnya', 'Lainnya')], max_length=20),
        ),
    ]
