# Generated by Django 5.2.4 on 2025-07-14 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_benefit_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='keterangan',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PenerimaBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('susu', 'Susu'), ('telur_susu', 'Telur + Susu'), ('lainnya', 'Lainnya')], max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
        ),
    ]
